/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author Notebook
 */
@Entity
public class ADDRESS_ENTITY implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long ADDRESS_PK;

    @Basic(optional = false)
    private String STREETNAME;

    @Basic(optional = false)
    private int HOUSENUMBER;

    @Basic(optional = false)
    private int POSTALCODE;

    @Basic(optional = false)
    private String CITY;

    @Basic
    private String STATE;

    @Basic(optional = false)
    private String COUNTRY;

    public Long getADDRESS_PK() {
        return this.ADDRESS_PK;
    }

    public void setADDRESS_PK(Long ADDRESS_PK) {
        this.ADDRESS_PK = ADDRESS_PK;
    }

    public String getSTREETNAME() {
        return this.STREETNAME;
    }

    public void setSTREETNAME(String STREETNAME) {
        this.STREETNAME = STREETNAME;
    }

    public int getHOUSENUMBER() {
        return this.HOUSENUMBER;
    }

    public void setHOUSENUMBER(int HOUSENUMBER) {
        this.HOUSENUMBER = HOUSENUMBER;
    }

    public int getPOSTALCODE() {
        return this.POSTALCODE;
    }

    public void setPOSTALCODE(int POSTALCODE) {
        this.POSTALCODE = POSTALCODE;
    }

    public String getCITY() {
        return this.CITY;
    }

    public void setCITY(String CITY) {
        this.CITY = CITY;
    }

    public String getSTATE() {
        return this.STATE;
    }

    public void setSTATE(String STATE) {
        this.STATE = STATE;
    }

    public String getCOUNTRY() {
        return this.COUNTRY;
    }

    public void setCOUNTRY(String COUNTRY) {
        this.COUNTRY = COUNTRY;
    }

}
