/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import javax.persistence.Entity;

/**
 * @author Notebook
 */
@Entity
public class ADMINISTRATOR_ENTITY extends PERSON_ENTITY implements Serializable {

}
