/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Notebook
 */
@Entity
public class COURSE_ENTITY implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long COURSE_PK;

    @Basic
    private String COURSE_NAME;

    @Basic
    private String LECTURER;

    @OneToMany(targetEntity = GRADE_ENTITY.class)
    private List<GRADE_ENTITY> GRADE_ENTITies;

    public Long getCOURSE_PK() {
        return this.COURSE_PK;
    }

    public void setCOURSE_PK(Long COURSE_PK) {
        this.COURSE_PK = COURSE_PK;
    }

    public String getCOURSE_NAME() {
        return this.COURSE_NAME;
    }

    public void setCOURSE_NAME(String COURSE_NAME) {
        this.COURSE_NAME = COURSE_NAME;
    }

    public String getLECTURER() {
        return this.LECTURER;
    }

    public void setLECTURER(String LECTURER) {
        this.LECTURER = LECTURER;
    }

    public List<GRADE_ENTITY> getGRADE_ENTITies() {
        return this.GRADE_ENTITies;
    }

    public void setGRADE_ENTITies(List<GRADE_ENTITY> GRADE_ENTITies) {
        this.GRADE_ENTITies = GRADE_ENTITies;
    }

}
