/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Kurs
 */
@Entity
public class COURSE_ENTITY implements Serializable {

    public COURSE_ENTITY() {
    }

    public COURSE_ENTITY(String COURSE_PK, String COURSE_NAME, int LECTURER_PK, int SEMESTER, String STUDY) {
        this.setCOURSE_PK(Long.parseLong(COURSE_PK));
        this.setCOURSE_NAME(COURSE_NAME);
        this.setLECTURER_PK(LECTURER_PK);
        this.setSEMESTER(SEMESTER);
        this.setSTUDY(STUDY);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long COURSE_PK;

    @Basic
    private String COURSE_NAME;

    @Basic
    private int LECTURER_PK;

    @Basic
    private int SEMESTER;

    @Basic
    private String STUDY;

    @OneToMany(targetEntity = GRADE_ENTITY.class)
    private List<GRADE_ENTITY> GRADE_ENTITies;

    public Long getCOURSE_PK() {
        return this.COURSE_PK;
    }

    public void setCOURSE_PK(Long COURSE_PK) {
        this.COURSE_PK = COURSE_PK;
    }

    public String getCOURSE_NAME() {
        return this.COURSE_NAME;
    }

    public void setCOURSE_NAME(String COURSE_NAME) {
        this.COURSE_NAME = COURSE_NAME;
    }

    public int getLECTURER_PK() {
        return this.LECTURER_PK;
    }

    public void setLECTURER_PK(int LECTURER_PK) {
        this.LECTURER_PK = LECTURER_PK;
    }

    public List<GRADE_ENTITY> getGRADE_ENTITies() {
        return this.GRADE_ENTITies;
    }

    public void setGRADE_ENTITies(List<GRADE_ENTITY> GRADE_ENTITies) {
        this.GRADE_ENTITies = GRADE_ENTITies;
    }

    public int getSEMESTER() {
        return SEMESTER;
    }

    public void setSEMESTER(int SEMESTER) {
        this.SEMESTER = SEMESTER;
    }

    public String getSTUDY() {
        return STUDY;
    }

    public void setSTUDY(String STUDY) {
        this.STUDY = STUDY;
    }

}
