/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.ForeignKey;
/**
 * Kurs
 */
@Entity
public class COURSE_ENTITY implements Serializable {
    private LECTURER_ENTITY lecturer;
    
    public COURSE_ENTITY() {
    }

    public COURSE_ENTITY(String COURSE_COURSE_PK, String COURSE_NAME, int SEMESTER, String STUDY, LECTURER_ENTITY lecturer) {
        this.setCOURSE_COURSE_PK(Long.parseLong(COURSE_COURSE_PK));
        this.setCOURSE_NAME(COURSE_NAME);
        this.setSEMESTER(SEMESTER);
        this.setSTUDY(STUDY);
        this.setLecturer(lecturer);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long COURSE_PK;

    @Basic
    private String COURSE_NAME;

    @Basic
    private int SEMESTER;

    @Basic
    private String STUDY;

    @OneToMany(targetEntity = GRADE_ENTITY.class, cascade = CascadeType.REMOVE)
    private List<GRADE_ENTITY> GRADE_ENTITies;

    public Long getCOURSE_COURSE_PK() {
        return this.COURSE_PK;
    }

    public void setCOURSE_COURSE_PK(Long COURSE_COURSE_PK) {
        this.COURSE_PK = COURSE_COURSE_PK;
    }

    public String getCOURSE_NAME() {
        return this.COURSE_NAME;
    }

    public void setCOURSE_NAME(String COURSE_NAME) {
        this.COURSE_NAME = COURSE_NAME;
    }

    @ManyToOne()
    public LECTURER_ENTITY getLecturer(){
        return lecturer;
    }
    
    public void setLecturer(LECTURER_ENTITY lecturer){
        this.lecturer = lecturer;
    }

    public List<GRADE_ENTITY> getGRADE_ENTITies() {
        return this.GRADE_ENTITies;
    }

    public void setGRADE_ENTITies(List<GRADE_ENTITY> GRADE_ENTITies) {
        this.GRADE_ENTITies = GRADE_ENTITies;
    }

    public int getSEMESTER() {
        return SEMESTER;
    }

    public void setSEMESTER(int SEMESTER) {
        this.SEMESTER = SEMESTER;
    }

    public String getSTUDY() {
        return STUDY;
    }

    public void setSTUDY(String STUDY) {
        this.STUDY = STUDY;
    }

}
