/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Noten/Ergebnisse
 */
@Entity
public class GRADE_ENTITY implements Serializable {
    private STUDENT_ENTITY student;
    private COURSE_ENTITY course;
    
    public GRADE_ENTITY () {
    }
    
    public GRADE_ENTITY (String GRADE_PK, COURSE_ENTITY COURSE, int GRADE, STUDENT_ENTITY STUDENT) {
        this.setGRADE_PK(Long.parseLong(GRADE_PK));
        this.setCOURSE(COURSE);
        this.setGRADE(GRADE);
        this.setSTUDENT(STUDENT);
    }
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long GRADE_PK;



    @Basic
    private int GRADE;

    public Long getGRADE_PK() {
        return this.GRADE_PK;
    }

    public void setGRADE_PK(Long GRADE_PK) {
        this.GRADE_PK = GRADE_PK;
    }

    public int getGRADE() {
        return this.GRADE;
    }

    public void setGRADE(int GRADE) {
        this.GRADE = GRADE;
    }
    
     @ManyToOne(cascade = CascadeType.REMOVE)
    public COURSE_ENTITY getCOURSE(){
        return course;
    }
    
    public void setCOURSE(COURSE_ENTITY course){
        this.course = course;
    }
    
    @ManyToOne()
    public STUDENT_ENTITY getSTUDENT(){
        return student;
    }
    
    public void setSTUDENT(STUDENT_ENTITY student){
        this.student = student;
    }
}
