/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Notebook
 */
@Entity
public class LECTURER_ENTITY extends PERSON_ENTITY implements Serializable {

    @Basic(optional = false)
    private int EMPLOEE_NR;

    @Basic(optional = false)
    private String FIELD_OF_STUDY_1;

    @Basic
    private String FIELD_OF_STUDY_2;

    @OneToMany(targetEntity = COURSE_ENTITY.class)
    private List<COURSE_ENTITY> COURSE_ENTITies;

    public int getEMPLOEE_NR() {
        return this.EMPLOEE_NR;
    }

    public void setEMPLOEE_NR(int EMPLOEE_NR) {
        this.EMPLOEE_NR = EMPLOEE_NR;
    }

    public String getFIELD_OF_STUDY_1() {
        return this.FIELD_OF_STUDY_1;
    }

    public void setFIELD_OF_STUDY_1(String FIELD_OF_STUDY_1) {
        this.FIELD_OF_STUDY_1 = FIELD_OF_STUDY_1;
    }

    public String getFIELD_OF_STUDY_2() {
        return this.FIELD_OF_STUDY_2;
    }

    public void setFIELD_OF_STUDY_2(String FIELD_OF_STUDY_2) {
        this.FIELD_OF_STUDY_2 = FIELD_OF_STUDY_2;
    }

    public List<COURSE_ENTITY> getCOURSE_ENTITies() {
        return this.COURSE_ENTITies;
    }

    public void setCOURSE_ENTITies(List<COURSE_ENTITY> COURSE_ENTITies) {
        this.COURSE_ENTITies = COURSE_ENTITies;
    }

}
