/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Notebook
 */
@Entity
public class LECTURE_ENT implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long LECTURE_PK;

    @Basic
    private String NAME;

    @Basic
    private String DESCRIPTION;

    @Basic
    private int SEMESTER;

    @Basic
    private String FIELD_OF_STUDY;

    @Basic
    private String DEGREE_OF_STUDY;

    @ManyToMany(targetEntity = STUDENT_ENT.class)
    private List<STUDENT_ENT> STUDENT_ENTs;

    public Long getLECTURE_PK() {
        return this.LECTURE_PK;
    }

    public void setLECTURE_PK(Long LECTURE_PK) {
        this.LECTURE_PK = LECTURE_PK;
    }

    public String getNAME() {
        return this.NAME;
    }

    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    public String getDESCRIPTION() {
        return this.DESCRIPTION;
    }

    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION;
    }

    public int getSEMESTER() {
        return this.SEMESTER;
    }

    public void setSEMESTER(int SEMESTER) {
        this.SEMESTER = SEMESTER;
    }

    public String getFIELD_OF_STUDY() {
        return this.FIELD_OF_STUDY;
    }

    public void setFIELD_OF_STUDY(String FIELD_OF_STUDY) {
        this.FIELD_OF_STUDY = FIELD_OF_STUDY;
    }

    public String getDEGREE_OF_STUDY() {
        return this.DEGREE_OF_STUDY;
    }

    public void setDEGREE_OF_STUDY(String DEGREE_OF_STUDY) {
        this.DEGREE_OF_STUDY = DEGREE_OF_STUDY;
    }

    public List<STUDENT_ENT> getSTUDENT_ENTs() {
        return this.STUDENT_ENTs;
    }

    public void setSTUDENT_ENTs(List<STUDENT_ENT> STUDENT_ENTs) {
        this.STUDENT_ENTs = STUDENT_ENTs;
    }

}
