/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Notebook
 */
@Entity
public class LECTURER_ENTITY extends PERSON_ENTITY implements Serializable, PERSON {

    public LECTURER_ENTITY(){}

    public LECTURER_ENTITY(String PERSON_PK, String ADMINSEX, Date BIRTHDATE, int EMPLOYEE_NR, String FIELD_OF_STUDY_1, String FIELD_OF_STUDY_2, String FIRST_NAME, boolean ISVALID, String LAST_NAME, String PASSWORD, int SVNR, String TITLE, String USERNAME){
        this.setPERSON_PK(Long.parseLong(PERSON_PK));
        this.setADMINSEX(ADMINSEX);
        this.setBIRTHDATE(BIRTHDATE);
        this.setEMPLOEE_NR(EMPLOYEE_NR);
        this.setFIELD_OF_STUDY_1(FIELD_OF_STUDY_1);
        this.setFIELD_OF_STUDY_2(FIELD_OF_STUDY_2);
        this.setFIRSTNAME(FIRST_NAME);
        this.setISVALID(ISVALID);
        this.setLASTNAME(LAST_NAME);
        this.setPASSWORD(PASSWORD);
        this.setSSN(SVNR);
        this.setTITLE(TITLE);
        this.setUSERNAME(USERNAME);
    }
    
    
    @Basic(optional = false)
    private int EMPLOEE_NR;

    @Basic(optional = false)
    private String FIELD_OF_STUDY_1;

    @Basic
    private String FIELD_OF_STUDY_2;

    @OneToMany(targetEntity = COURSE_ENTITY.class)
    private List<COURSE_ENTITY> COURSE_ENTITies;

    public int getEMPLOEE_NR() {
        return this.EMPLOEE_NR;
    }

    public void setEMPLOEE_NR(int EMPLOEE_NR) {
        this.EMPLOEE_NR = EMPLOEE_NR;
    }

    public String getFIELD_OF_STUDY_1() {
        return this.FIELD_OF_STUDY_1;
    }

    public void setFIELD_OF_STUDY_1(String FIELD_OF_STUDY_1) {
        this.FIELD_OF_STUDY_1 = FIELD_OF_STUDY_1;
    }

    public String getFIELD_OF_STUDY_2() {
        return this.FIELD_OF_STUDY_2;
    }

    public void setFIELD_OF_STUDY_2(String FIELD_OF_STUDY_2) {
        this.FIELD_OF_STUDY_2 = FIELD_OF_STUDY_2;
    }

    public List<COURSE_ENTITY> getCOURSE_ENTITies() {
        return this.COURSE_ENTITies;
    }

    public void setCOURSE_ENTITies(List<COURSE_ENTITY> COURSE_ENTITies) {
        this.COURSE_ENTITies = COURSE_ENTITies;
    }
    
      @Override
    public PERSON_ENTITY getClone(){
        LECTURER_ENTITY lecturer = null;
        try {
            lecturer = (LECTURER_ENTITY) super.clone();
            
        }
        catch(CloneNotSupportedException ex){
            System.out.println(ex.getMessage());
        }
        return lecturer;
    }
}
