/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.sql.Date;
import javax.persistence.Basic;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * @author Notebook
 */
@MappedSuperclass
public abstract class PERSON_ENT implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long PERSON_PK;

    @Basic
    private String FIRST_NAME;

    @Basic
    private String LAST_NAME;

    @Basic
    private String DEGREE;

    @Basic
    private char ADMINISTRATIVE_SEX;

    @Basic
    private int SVNR;

    @Basic
    private Date BIRTH_DATE;

    public Long getPERSON_PK() {
        return this.PERSON_PK;
    }

    public void setPERSON_PK(Long PERSON_PK) {
        this.PERSON_PK = PERSON_PK;
    }

    public String getFIRST_NAME() {
        return this.FIRST_NAME;
    }

    public void setFIRST_NAME(String FIRST_NAME) {
        this.FIRST_NAME = FIRST_NAME;
    }

    public String getLAST_NAME() {
        return this.LAST_NAME;
    }

    public void setLAST_NAME(String LAST_NAME) {
        this.LAST_NAME = LAST_NAME;
    }

    public String getDEGREE() {
        return this.DEGREE;
    }

    public void setDEGREE(String DEGREE) {
        this.DEGREE = DEGREE;
    }

    public char getADMINISTRATIVE_SEX() {
        return this.ADMINISTRATIVE_SEX;
    }

    public void setADMINISTRATIVE_SEX(char ADMINISTRATIVE_SEX) {
        this.ADMINISTRATIVE_SEX = ADMINISTRATIVE_SEX;
    }

    public int getSVNR() {
        return this.SVNR;
    }

    public void setSVNR(int SVNR) {
        this.SVNR = SVNR;
    }

    public Date getBIRTH_DATE() {
        return this.BIRTH_DATE;
    }

    public void setBIRTH_DATE(Date BIRTH_DATE) {
        this.BIRTH_DATE = BIRTH_DATE;
    }

}
