/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;

/**
 * @author Notebook
 */
@Entity
public class STUDENT_ENT extends PERSON_ENT implements Serializable {

    @Basic
    private String STUDENT_NUMBER;

    @ManyToMany(targetEntity = LECTURE_ENT.class, mappedBy = "STUDENT_ENTs")
    private List<LECTURE_ENT> LECTURE_ENTs;

    public String getSTUDENT_NUMBER() {
        return this.STUDENT_NUMBER;
    }

    public void setSTUDENT_NUMBER(String STUDENT_NUMBER) {
        this.STUDENT_NUMBER = STUDENT_NUMBER;
    }

    public List<LECTURE_ENT> getLECTURE_ENTs() {
        return this.LECTURE_ENTs;
    }

    public void setLECTURE_ENTs(List<LECTURE_ENT> LECTURE_ENTs) {
        this.LECTURE_ENTs = LECTURE_ENTs;
    }

}
