/**
 * This file was generated by the JPA Modeler
 */
package project_entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author Notebook
 */
@Entity
public class TEACHER_ENT extends PERSON_ENT implements Serializable {

    @Basic
    private boolean IS_INTERNAL_LECTOR;

    @OneToMany(targetEntity = LECTURE_ENT.class)
    private List<LECTURE_ENT> LECTURE_ENTs;

    public boolean isIS_INTERNAL_LECTOR() {
        return this.IS_INTERNAL_LECTOR;
    }

    public void setIS_INTERNAL_LECTOR(boolean IS_INTERNAL_LECTOR) {
        this.IS_INTERNAL_LECTOR = IS_INTERNAL_LECTOR;
    }

    public List<LECTURE_ENT> getLECTURE_ENTs() {
        return this.LECTURE_ENTs;
    }

    public void setLECTURE_ENTs(List<LECTURE_ENT> LECTURE_ENTs) {
        this.LECTURE_ENTs = LECTURE_ENTs;
    }

}
